scrape_configs:
  - job_name: "rabbitmq"
    scrape_interval: 15s
    static_configs:
      - targets: ["rabbitmq:15692"]

  - job_name: "golang-server"
    scrape_interval: 5s
    static_configs:
      - targets: ["server:2112"]
